"""add new column

Revision ID: 2d6a6ca1f659
Revises: 9ecd32cc4a86
Create Date: 2017-01-11 13:29:31.680337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6a6ca1f659'
down_revision = '9ecd32cc4a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('name', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_question_name'), 'question', ['name'], unique=False)
    op.add_column('upload file', sa.Column('uid', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_upload file_uid'), 'upload file', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload file_uid'), table_name='upload file')
    op.drop_column('upload file', 'uid')
    op.drop_index(op.f('ix_question_name'), table_name='question')
    op.drop_column('question', 'name')
    # ### end Alembic commands ###
