"""modify column

Revision ID: 9ecd32cc4a86
Revises: 6d4cf8deaf97
Create Date: 2016-12-26 16:32:50.772607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ecd32cc4a86'
down_revision = '6d4cf8deaf97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload file', 'count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_index('ix_upload file_link', table_name='upload file')
    op.drop_column('upload file', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload file', sa.Column('link', mysql.VARCHAR(length=1024), nullable=True))
    op.create_index('ix_upload file_link', 'upload file', ['link'], unique=False)
    op.alter_column('upload file', 'count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
