"""add user total num column

Revision ID: c54de427a522
Revises: 2d6a6ca1f659
Create Date: 2017-01-11 13:55:17.288985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c54de427a522'
down_revision = '2d6a6ca1f659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload file', sa.Column('user_total_num', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_upload file_user_total_num'), 'upload file', ['user_total_num'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload file_user_total_num'), table_name='upload file')
    op.drop_column('upload file', 'user_total_num')
    # ### end Alembic commands ###
